# Generated by Django 5.2.5 on 2025-08-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='car',
        ),
        migrations.AddField(
            model_name='sale',
            name='car',
            field=models.ManyToManyField(to='main.car'),
        ),
    ]
