# Generated by Django 5.2.5 on 2025-08-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_sale_car_sale_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='2.1-databases-cars/images'),
        ),
    ]
